name: CoordinatesPlugin
main: com.parryproject.CoordinatesPlugin
version: 1.1
api-version: 1.20
commands:
  coords:
    description: Enable or disable coordinates display on your screen
    usage: /coords <on|off>
